#	Database
#######################################
data.mongodb.uri=mongodb://mongoadmin:secret@localhost:27888/fse
data.mongodb.schema-name=FSE_EDS

spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB