#	Database
#######################################
data.mongodb.uri=mongodb://mongoadmin:secret@localhost:27888/fse
data.mongodb.schema-name=FSE_EDS


otel.traces.exporter=none
otel.logs.exporter=none
otel.metrics.exporter=none
otel.propagators=tracecontext,baggage